aspirasi/urls.py
from django.urls import path
from aspirasi.views import show_aspirasi, show_json, add_aspirasi_ajax, show_aspirasi_pendatang, show_json_user, show_json_user, show_aspirasi_user, add_aspirasi_flutter

app_name = 'aspirasi'

urlpatterns = [
    path('', show_aspirasi, name='show_aspirasi'),
    path('json/', show_json, name='show_json'),
    path('add/', add_aspirasi_ajax, name='add_aspirasi_ajax'),
    path('show-aspirasi/', show_aspirasi_pendatang, name='show_aspirasi_pendatang'),
    path('json-user/', show_json_user, name='show_json_user'),
    path('aspirasi-user/', show_aspirasi_user, name='show_aspirasi_user'),
    path('add-aspirasi-flutter/', add_aspirasi_flutter, name='show_aspirasi_flutter'),



]

depoksmartcity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from depoksmartcity import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('kependudukan/', include('kependudukan.urls')),
    path('perpustakaan/', include('perpustakaan.urls')),
    path('aspirasi/', include('aspirasi.urls')),
    path('restaurants/', include('restaurants.urls')),
    path('kesehatan/', include('kesehatan.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

homepage/urls.py
from django.urls import path
from .views import index, login_user, register_user, logout_user, login_flutter, register_flutter, logout_flutter

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    path('logout-flutter/', logout_flutter, name='logout_flutter'),
    path('login-flutter/', login_flutter, name='login_flutter'),
    path('register-flutter/', register_flutter, name='register_flutter'),

]

aspirasi/models.py
from django.db import models
from django.contrib.auth.models import User

class Aspirasi(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    aspirasi = models.TextField()

aspirasi/forms.py
from django import forms
from .models import Aspirasi

class AspirasiForm(forms.ModelForm):
    class Meta:
        model = Aspirasi
        exclude = ('user', )

aspirasi/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import aspirasi
from aspirasi.forms import AspirasiForm
from aspirasi.models import Aspirasi
from django.http import JsonResponse, HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.contrib.auth.models import User
from django.shortcuts import redirect
import json
from django.views.decorators.csrf import csrf_exempt

def show_aspirasi(request):
    data_aspirasi = Aspirasi.objects.all()
    form = AspirasiForm()
    context = {
        'data_aspirasi': data_aspirasi,
        'form' : form,
    }
    return render(request, "aspirasi.html", context)

def show_json(request):
    data_aspirasi = Aspirasi.objects.all()
    return HttpResponse(serializers.serialize("json", data_aspirasi))

@login_required(login_url='/login/')
def show_aspirasi_pendatang(request):
    data_aspirasi = Aspirasi.objects.all()
    context = {
        'data_aspirasi': data_aspirasi,
    }
    return render(request, "aspirasi.html", context)


def add_aspirasi_ajax(request):
    if request.method == "POST":
        form = AspirasiForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = User.objects.get(username=request.user.username)
            obj.save()
            return HttpResponse(b"CREATED", status=201)
            
    return HttpResponseNotFound()

def show_json_user(request):
    data_aspirasi_user = Aspirasi.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data_aspirasi_user))

@login_required(login_url='/login/')
def show_aspirasi_user(request):
    data_aspirasi_user = Aspirasi.objects.filter(user=request.user)
    context = {
        'data_aspirasi_user': data_aspirasi_user,
    }
    return render(request, "aspirasiUser.html", context)

@csrf_exempt
def add_aspirasi_flutter(request):
    data = json.loads(request.body)
    aspirasi = data['aspirasi']
    user = User.objects.get(username=request.user.username)
    if request.method == 'POST':
        aspirasi = Aspirasi(aspirasi=aspirasi, user=user)
        aspirasi.save()
        return JsonResponse({
                "status": True,
                "message": "Successfull!"
            }, status=200)
    return JsonResponse({
            "status": False,
            "message": "Failed!"
    }, status=502)

aspirasi/templates/aspirasi.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div style="overflow-x :hidden;">
  <nav class="navbar" style="background-color: #232b2b;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1">
        <b style="color:white">Welcome! {{user}}</b></span>
      <form class="form-inline">
      <a class="btn btn-info" href="{% url 'homepage:index' %}" role="button">Kembali</a>
      {% if request.user.is_authenticated %}
      <a class="btn btn-info" href="{% url 'homepage:logout' %}" role="button">Logout</a>
      {% else %}
      <a class="btn btn-info" href="{% url 'homepage:login' %}" role="button">Login</a>
      {% endif %}
      </form>
    </div>
  </nav>


  <link rel="stylesheet" href="{% static 'css/aspirasi.css' %}">
  <div class="backgroundImages">
    <section id="aspirasi" >

        <div class="row">
            <div class="col">
                <h2 class="text-center text-dark font-weight-bold my-5">Aspirasi</h2>
            </div>
        </div>
        
        
        <div style="display:inline-flex">
            <div class="col-md-4 d-flex p-0 flex-column align-items-center" style="margin-right:225px;margin-left:280px">
                <div style="background: #ADD8E6; border-radius: 24px; padding-right:20px; width:380px;padding-left:20px;padding-top:20px;padding-bottom:20px" >
                    <div class="col m-2">
                        {% if request.user.is_authenticated %}
                            <!-- form aspirasi -->
                            <form method="POST" id="postAspirasi" onsubmit="addAspirasi(`{% url 'aspirasi:add_aspirasi_ajax' %}`);return false" >
                                <p class="w-100 justify-content-center my-1">Halo, <span style="color: #67809F;">{{ user }}</span>!</p>
                                {% csrf_token %}
                                {{ form }}
                                <button type="submit" value="Submit" class="tombol btn btn-primary mx-auto my-2">
                                    Submit
                                </button>
                            </form>
                        {% else %}
                            <p class="w-100 justify-content-center my-1"">Halo, <span style="color: #67809F;">Pendatang</span>!</p>
                            <p class="w-100 justify-content-center my-1"">Login untuk menyalurkan aspirasi Anda</p>

                            <form action="{% url 'aspirasi:show_aspirasi_pendatang' %}">
                            <button type="submit" class="tombol btn btn-primary mx-auto my-2">Login</button>
                            </form>
     
                        {% endif %}
                        <a class="btn btn-info" href="{% url 'aspirasi:show_aspirasi_user' %}" role="button">Cek Aspirasi</a>
                    </div>
                </div>
            </div>

            <div class="col-md-8 p-0" style="max-height: 100%;text-align: center;">
              <p>
              <div id="output" class="outputStyle">
            
              <!-- output aspirasi -->
              </div>
          </div>
        
        </div>




    </section>
    </div>
</div>
    <script src="{% static 'js/aspirasi.js' %}"></script>
{% endblock content %}

aspirasi/templates/aspirasiUser.html
{% extends 'base.html' %}
{% load static %}
 {% block content %}

 <link rel="stylesheet" href="{% static 'css/aspirasi.css' %}">
<style>
      table{
    border: 1px solid;
}

th{
    border: 1px solid;
}
.cards{
    border: 1px solid black;
    margin: 13px;
    padding: 15px;
    width: 600px;
    display: inline-block;
    background-color: #ADD8E6;
    border: 1px solid #c9c9c9;
    border-radius: 7%
  }

.nowrap {
    white-space: nowrap ;
}

.buttonwrapper{
    display: flex;
}

.centeredtext{
    text-align:center; 

}
.button{
    color:blue;
}
header{
    text-align: center;
}
body{
    background: hsla(192, 80%, 51%, 1);

    background: linear-gradient(90deg, hsla(192, 80%, 51%, 1) 0%, hsla(355, 85%, 63%, 1) 94%);

    background: -moz-linear-gradient(90deg, hsla(192, 80%, 51%, 1) 0%, hsla(355, 85%, 63%, 1) 94%);

    background: -webkit-linear-gradient(90deg, hsla(192, 80%, 51%, 1) 0%, hsla(355, 85%, 63%, 1) 94%);

    filter: progid: DXImageTransform.Microsoft.gradient( startColorstr="#1DBDE6", endColorstr="#F1515E", GradientType=1 );
    width: 100vw;
    min-height: 100vh;
}

textarea {
    resize: none;
    width: 300px;
    height: 30px;
}

.cards:hover {
    box-shadow: 0 8px 16px 0 rgba(0,0,0,0.2);
}

</style>

    <nav class="navbar" style="background-color: #232b2b;">
      <div class="container-fluid">
        <span class="navbar-brand mb-0 h1">
          <b style="color:white">Welcome! {{user}}</b></span>
        <form class="form-inline">
        <a class="btn btn-info" href="{% url 'aspirasi:show_aspirasi' %}" role="button">Kembali</a>
        {% if request.user.is_authenticated %}
        <a class="btn btn-info" href="{% url 'homepage:logout' %}" role="button">Logout</a>
        {% else %}
        <a class="btn btn-info" href="{% url 'homepage:login' %}" role="button">Login</a>
        {% endif %}
        </form>
      </div>
    </nav>

<br></br>
<h1 class="centeredtext" >Aspirasi Anda :</h1>
<br></br>
    <div class="card-deck">
    {% for x in data_aspirasi_user %}
      <div class="cards" >
        <p>
        <span class="nowrap">{{x.aspirasi}}</span>
        </p>
      </div>
    {% endfor %}
    </div>


  <br></br>
 {% endblock content %}