aspirasi/urls.py
from django.urls import path
from aspirasi.views import show_aspirasi, show_json, add_aspirasi_ajax, show_aspirasi_pendatang, show_json_user, show_json_user, show_aspirasi_user, add_aspirasi_flutter

app_name = 'aspirasi'

urlpatterns = [
    path('', show_aspirasi, name='show_aspirasi'),
    path('json/', show_json, name='show_json'),
    path('add/', add_aspirasi_ajax, name='add_aspirasi_ajax'),
    path('show-aspirasi/', show_aspirasi_pendatang, name='show_aspirasi_pendatang'),
    path('json-user/', show_json_user, name='show_json_user'),
    path('aspirasi-user/', show_aspirasi_user, name='show_aspirasi_user'),
    path('add-aspirasi-flutter/', add_aspirasi_flutter, name='show_aspirasi_flutter'),



]

depoksmartcity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from depoksmartcity import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('kependudukan/', include('kependudukan.urls')),
    path('perpustakaan/', include('perpustakaan.urls')),
    path('aspirasi/', include('aspirasi.urls')),
    path('restaurants/', include('restaurants.urls')),
    path('kesehatan/', include('kesehatan.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

homepage/urls.py
from django.urls import path
from .views import index, login_user, register_user, logout_user, login_flutter, register_flutter, logout_flutter

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    path('logout-flutter/', logout_flutter, name='logout_flutter'),
    path('login-flutter/', login_flutter, name='login_flutter'),
    path('register-flutter/', register_flutter, name='register_flutter'),

]

kependudukan/urls.py
from django.urls import path
from kependudukan.views import show_kependudukan, show_request_ktp, show_json, show_request_ktp_json, add_request, get_kelurahan, show_all_request_ktp_json, add_request_flutter, show_request_ktp_json_flutter

app_name = 'kependudukan'

urlpatterns = [
    path('', show_kependudukan, name='show_kependudukan'),
    path('request-ktp', show_request_ktp, name='show_request_ktp'),
    path('request-ktp/get-kelurahan', get_kelurahan),
    path('json', show_json, name='show_json'),
    path('request-ktp/json', show_request_ktp_json, name='show_request_ktp_json'),
    path('all-request-ktp/json', show_all_request_ktp_json, name='show_all_request_ktp_json'),
    path('request-ktp/add', add_request, name='add_request'),
    path('request-ktp/add-flutter', add_request_flutter, name='add_request_flutter'),
    path('request-ktp/json-flutter', show_request_ktp_json_flutter, name='show_request_ktp_json_flutter'),

    
]

kesehatan/urls.py
from django.urls import path
from .views import show_main, registrasi, show_healthFacility, show_healthFacility_json, show_appointment_json, create_appointment, delete_appointment, show_registered_patient_page, get_appointment_flutter_json_by_userId, get_patient_flutter_by_userId, add_patient_flutter, add_appointment_flutter, delete_appointment_flutter

app_name = 'kesehatan'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('health-facility/', show_healthFacility, name='health-facility'),
    path('health-facility/json/', show_healthFacility_json, name="health-facility-json"),
    path('registrasi/', registrasi, name='registrasi'),
    path('create-appointment/', create_appointment, name='create-appointment'),
    path('delete-appointment/<int:id>', delete_appointment, name='delete-appointment'),
    path('registered-patient/', show_registered_patient_page, name='registered-patient'),
    path('create-appointment/json/', show_appointment_json, name='appointment-json'),
    path('create-appointment-flutter/', add_appointment_flutter, name='create-appointment-flutter'),
    path('create-appointment-flutter/<int:id>/json', get_appointment_flutter_json_by_userId, name="appointment-json-by-id"),
    path('show-patient-flutter/<int:id>/json', get_patient_flutter_by_userId, name="appointment-json-by-id"),
    path('registrasi-flutter/', add_patient_flutter, name='add-patient-appointment'),
     path('delete-appointment-flutter/<int:id>', delete_appointment_flutter, name='delete-appointment-flutter'),
]

perpustakaan/urls.py
from django.urls import path
from .views import (get_book, get_book_by_id_json, get_book_json, get_book_by_id,
                    get_book_review_id_json,get_book_history_active_id_json,
                    get_book_history_done_id_json, get_author_by_id_json, get_publisher_by_id_json,
                    borrow, review, return_book, borrow_json, return_book_json, review_json)
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from depoksmartcity import settings

app_name = 'perpustakaan'

urlpatterns = [
    path('', get_book, name='get_book'),
    path('json', get_book_json, name='get_book_json'),
    path('book/<int:id>', get_book_by_id, name='get_book_by_id'),
    path('book/<int:id>/json', get_book_by_id_json, name='get_book_by_id_json'),
    path('author/<int:id>/json', get_author_by_id_json, name="get_author_by_id_json"),
    path('publisher/<int:id>/json', get_publisher_by_id_json, name="get_publisher_by_id_json"),
    path('book/borrow/<int:id>', borrow, name='borrow'),
    path('book/<int:id>/borrow', borrow_json, name='borrow_json'),
    path('book/return/<int:id>', return_book, name='return_book'),
    path('book/<int:id>/return', return_book_json, name='return_book_json'),
    path('book/review/<int:id>', review, name='review'),
    path('book/<int:id>/review', review_json, name='review_json'),
    path('book/history/active/<int:id>', get_book_history_active_id_json, name='get_book_history_active_id_json'),
    path('book/history/done/<int:id>', get_book_history_done_id_json, name='get_book_history_done_id_json'),
    path('book/review/<int:id>/json', get_book_review_id_json, name='get_book_review_id_json'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.urls import path
from restaurants.views import show_restaurants
from restaurants.views import show_json
from restaurants.views import review_json
from restaurants.views import create_review

app_name = 'restaurants'

urlpatterns = [
    path('', show_restaurants, name='restaurants'),
    path('json/', show_json, name='json'),
    path('json-rev/<int:pk>', review_json, name='rev_json'),
    path('create-review/', create_review, name='create-review')
]

restaurants/models.py
from django.db import models
from django.contrib.auth.models import User



# Create your models here.
class Restaurant(models.Model):
    name = models.TextField()
    lokasi = models.TextField()
    desc = models.TextField()
    img = models.URLField(default='')

class Reviews(models.Model):
    resto = models.ForeignKey(Restaurant, on_delete=models.CASCADE)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    review = models.TextField()

restaurants/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from restaurants.models import Restaurant
from restaurants.models import Reviews

#p
# Create your views here.
def show_json(request):
    restaurants = Restaurant.objects.all()
    return HttpResponse(serializers.serialize('json', restaurants))

def review_json(request, pk):
    reviews = Reviews.objects.filter(resto__pk=pk)
    return HttpResponse(serializers.serialize('json', reviews))

def show_restaurants(request, *args, **kwargs):	
    restaurants = Restaurant.objects.all()
    pk = kwargs.get('pk')
    reviews = Reviews.objects.filter(resto__pk=pk)
    context = {
        'list': restaurants,
        'reviews': reviews,
    }
    return render(request, "restaurant.html", context)

@login_required(login_url='/login/')
def create_review(request):
    if request.method == 'POST':
        review = request.POST.get('review')
        pk_resto = request.POST.get('pk_resto')
        print(review)

        a = Restaurant.objects.filter(pk=pk_resto)
        a = a.first()

        # bikin objek review
        # resto = request.resto
        new_reviews = Reviews(resto=a, review=review)
        new_reviews.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

restaurants/templates/restaurant.html
{% extends 'base.html' %}
{% load static %}


{% block meta %}
<script>window.CSRF_TOKEN = "{{ csrf_token }}"</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href={% static 'bootstrap.css' %} />
<link href={% static 'style.css' %} rel="stylesheet" />
<link rel="stylesheet" href="{% static 'css/restaurants.css' %}">


{% endblock meta %}

{% block content %}


<!-- <style>

    .card{
      border-radius: 4px;
      background: #fff;
      box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
      transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
      padding: 14px 80px 18px 36px;
      cursor: pointer;
    }

    .card:hover{
      transform: scale(1.05);
      box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }



    .vertical-scrollable>.row {
            position: absolute;
            top: 30px;
            bottom: 30px;
            left: 400px;
            width: 60%;
            overflow-x: hidden;
            overflow-y: scroll;
        }

    body {
            overflow-x: hidden;
            background-color: #DBE2EF;
        }

    #panel{
      transition: .5s;
    }

    #detail{
      height: 750px;
      background-color: rgb(255, 255, 255);
      box-shadow: 10px 10px 20px -10px rgba(158, 158, 158, 0.644);
      border-radius: 30px;
      transform: scale(0);
      transition: .5s;
      position: absolute;
      top: 40px;
      left: 10%;
      width: 80%;
      opacity: 1;
    }

    
    #review{
      height: 600px;
      background-color: rgb(255, 255, 255);
      box-shadow: 10px 10px 20px -10px rgba(158, 158, 158, 0.644);
      border-radius: 30px;
      transform: scale(0);
      transition: .5s;
      position: absolute;
      top: 40px;
      left: 10%;
      width: 80%;
      opacity: 1;
    }

    .close{
      font-size: 30px;
      cursor: pointer;
    }

    /* .card{
      transition: .5s;
      transform: translate(0px, 0px);
    }

    .card:hover{
      box-shadow: 10px 10px 40px -20px rgb(98, 98, 98);
      transform: translate(-5px,-5px);
    } */

    #card-pic {
      max-height: 110px;
      width: auto;
    }


</style> -->

<header class="header_section">
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="{% url 'homepage:index' %}">
          <span>
            Depok Smart City
          </span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class=""> </span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link pl-lg-0" href="{% url 'kependudukan:show_kependudukan' %}"> Kependudukan </a>
            </li>

            <li class="nav-item active">
              <a class="nav-link pl-lg-0" href="{% url 'restaurants:restaurants' %}"> Restoran </a>
            </li>

            <li class="nav-item active">
                <a class="nav-link pl-lg-0" href="{% url 'kesehatan:show_main' %}"> Kesehatan </a>
            </li>

            <li class="nav-item active">
              <a class="nav-link pl-lg-0" href="{% url 'perpustakaan:get_book' %}"> Perpustakaan </a>
            </li>

            <li class="nav-item active">
              <a class="nav-link pl-lg-0" href="{% url 'aspirasi:show_aspirasi' %}"> Aspirasi </a>
            </li>


            {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Hello, {{user.get_username}}!
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'homepage:logout' %}">Logout</a></li>
              </li>
            
            {% else %}
              <li class="nav-item active">
                <a class="nav-link pl-lg-0" href="{% url 'homepage:login' %}"> Login </a>
              </li>
            {% endif %}
          </ul>
        </div>
        
      </nav>
    </div>
  </header>

<br><br>

<div>
    
  <div>
    <h1 class="display-4 my-4 text-center">Catalog</h1>
  </div>

  <div class="container">
    <div class="row" id="panel">

    </div>

    <div class="row d-flex flex-wrap align-content-center p-3 border" id="detail">

    </div>

    <div class="row d-flex flex-wrap align-content-center p-3 border" id="review">


    </div>
  </div>

  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Create Review</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="" id="form" method="POST">
            {% csrf_token %}
                <div class="mb-md-5 mt-md-4 pb-5 px-2 py-2 bg-light text-dark rounded">
                    <div class="form-outline form-dark mb-4">
                        <input type="text" id="review-form" name="review" class="form-control" />
                      <label class="form-label" for="typeTitle">Insert Your Review</label>
                    </div>
            </form>
        </div>
        <div class="modal-footer">
            <td><button class="btn btn-outline-dark btn-lg px-5" id="button" data-bs-dismiss="modal" onsubmit="return false;" onclick="closeReview()">Create</button></td>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="modal" id="warnModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">NotLoggedIn</h5>
          <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>You need to be logged in to perform this action</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-dark btn-lg px-3"><a href="{% url 'homepage:login' %}">Log In</a></button>
          <button type="button" class="btn btn-outline-dark btn-lg px-3" data-bs-dismiss="modal">Cancel</button>
        </div>
      </div>
    </div>
  </div>

<script>
  $(document).ready(function()  {
    showCard();
  });

  async function getData() {
    return fetch("{% url 'restaurants:json' %}").then((res) => res.json())
  }
  
  async function showCard() {
    const panel = document.getElementById("panel");
    const list = await getData()
    let cards = ``
    list.forEach((item) => {
      cards+=`
      <div class="col-12 col-md-6 col-lg-4 py-2">
        <div class="card .bg-dark .bg-gradient rounded">
          <div class="card-body">
            <img id="card-pic" src="${item.fields.img}" class="card-img-top" alt="...">
              <br><br>
              <h5 class="card-title">${item.fields.name}</h5>
              <p class="card-text">${item.fields.lokasi}</p>
              <p class="card-text"></p> 
              <button class="btn btn-outline-dark btn-lg px-5" onclick="detail(${item.pk})">more</button>
          </div>
        </div>
      </div>
      `;
    });

    panel.innerHTML = cards;

  }

  async function detail(id){
    const list = await getData()
    const detailCard = document.getElementById("detail");
    detailCard.innerHTML = "";
    detailCard.style.transform = "scale(1)";
    panel.style.opacity = 1;
    panel.style.opacity = 0.5;
    detailCard.style.opacity = 1;
    let detail_div = ``

    list.forEach((item) => {
      if(item.pk == id) {
        detail_div = `
        <div class="w-100">
          <span class="close float-end" onclick="closeDetail()">&times;</span>
        </div>

        <div class="col-md-3 border-end p-4">
          <img class="w-100" src="${item.fields.img}" alt="..."/>
          <div>
            <h2 class="display-6 text-center">${item.fields.name}</h2>
          </div>
        </div>

        <div class="col-md-9">
          <div class="container vertical-scrollable">
            <div class="card" style="width: 48rem;">
              <div class="card-body">
                <h5 class="card-title"><b>Deskripsi</b></h5>
                <p class="card-text">${item.fields.desc}</p>
              </div>
            </div>

            <div class="card" style="width: 48rem;">
              <div class="card-body">
                <h5 class="card-title"><b>Lokasi</b></h5>
                <p class="card-text">${item.fields.lokasi}</p>
              </div>
            </div>
          </div>

          <br>
          <button class="btn btn-outline-dark btn-lg px-5" style = "position:relative; left:300px; " onclick="review(${item.pk})">Lihat Ulasan</button>
          
        `;
      }
    })
    detailCard.innerHTML = detail_div;
  }

  async function review(id){
    const list = await getData()
    const reviewCard = document.getElementById("review");
    reviewCard.innerHTML = "";
    reviewCard.style.transform = "scale(1)";
    panel.style.opacity = 1;
    panel.style.opacity = 0.5;
    reviewCard.style.opacity = 1;
    let review_div = ``
    
    let resto = ""

    list.forEach((item) => {
      if(item.pk == id) {
        resto = item
        console.log(item)
        console.log(resto)

        review_div = `
        <div class="w-100">
          <span class="close float-end" onclick="closeReview()">&times;</span>
          <h1><b>Ulasan</b></h1>
          {% if user.is_authenticated %}
          <button class="btn btn-outline-dark btn-lg px-5" data-bs-toggle="modal" data-bs-target="#exampleModal" >Create Review</button>
            {% else %}
            <button class="btn btn-outline-dark btn-lg px-5" data-bs-toggle="modal" data-bs-target="#warnModal" >Create Review</button>
            {% endif %}
        </div>

        
        
        <div class="container vertical-scrollable">
          <div class="row d-flex flex-wrap align-content-center p-3 border" id="reviewcontainer">
        
          </div>
        </div>


           `;
        
      }
    })
    

    document.getElementById("button").onclick = addReview(resto.pk)



    reviewCard.innerHTML = review_div;


  }

  function closeDetail(){
    const detailCard = document.getElementById("detail");
    const panel = document.getElementById("panel");
    detailCard.style.transform = "scale(0)";
    detailCard.style.opacity = 0;
    panel.style.opacity = 1;
  }

  function closeReview(){
    const reviewCard = document.getElementById("review");
    reviewCard.style.transform = "scale(0)";
    reviewCard.style.opacity = 0;
  }

  async function getReviews(id) {
    return fetch("/restaurants/json-rev/" + id).then((res) => res.json())
    
  }

  async function refreshReviews(id) {
    const review = document.getElementById("reviewcontainer");
    review.innerHTML = "";
    const reviews = await getReviews(id)
    let htmlString = ``
    reviews.forEach((item) => {
      if (item.fields.review != "" ) {
        htmlString += `
        <div class="card" style="width: 42rem;">
          <div class="card-body">
            <p class="card-text">${item.fields.review}</p>
          </div>
        </div>`;
      }

    });
    
    review.innerHTML = htmlString
    }
  
    async function addReview(id) {
      const list = await getData();
      let res = ''

      list.forEach((item) => {
        if (item.pk == id) {
          res = item
        }
      })
      console.log(res)
      

      const csrf = document.getElementsByName('csrfmiddlewaretoken')
      var formData = new FormData()
      formData.append('csrfmiddlewaretoken', csrf[0].value)
      formData.append('review', document.getElementById('review-form').value)
      formData.append('pk_resto', id)
      const input = document.getElementById('review-form');
      input.value = '';
      fetch("{% url 'restaurants:create-review' %}", {
            method: "POST",
            body: formData
        }).then(refreshReviews(id))
      refreshReviews(id)
      refreshReviews(id)
      refreshReviews(id)


      return false
    }

    const reviewCard = document.getElementById("review");
    reviewCard.style.transform = "scale(0)";
    reviewCard.style.opacity = 0;

</script>
<script src="{% static 'js/aspirasi.js' %}"></script>





{% endblock content %}