aspirasi/urls.py
from django.urls import path
from aspirasi.views import show_aspirasi, show_json, add_aspirasi_ajax, show_aspirasi_pendatang, show_json_user, show_json_user, show_aspirasi_user, add_aspirasi_flutter

app_name = 'aspirasi'

urlpatterns = [
    path('', show_aspirasi, name='show_aspirasi'),
    path('json/', show_json, name='show_json'),
    path('add/', add_aspirasi_ajax, name='add_aspirasi_ajax'),
    path('show-aspirasi/', show_aspirasi_pendatang, name='show_aspirasi_pendatang'),
    path('json-user/', show_json_user, name='show_json_user'),
    path('aspirasi-user/', show_aspirasi_user, name='show_aspirasi_user'),
    path('add-aspirasi-flutter/', add_aspirasi_flutter, name='show_aspirasi_flutter'),



]

depoksmartcity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from depoksmartcity import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('kependudukan/', include('kependudukan.urls')),
    path('perpustakaan/', include('perpustakaan.urls')),
    path('aspirasi/', include('aspirasi.urls')),
    path('restaurants/', include('restaurants.urls')),
    path('kesehatan/', include('kesehatan.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

homepage/urls.py
from django.urls import path
from .views import index, login_user, register_user, logout_user, login_flutter, register_flutter, logout_flutter

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    path('logout-flutter/', logout_flutter, name='logout_flutter'),
    path('login-flutter/', login_flutter, name='login_flutter'),
    path('register-flutter/', register_flutter, name='register_flutter'),

]

kependudukan/urls.py
from django.urls import path
from kependudukan.views import show_kependudukan, show_request_ktp, show_json, show_request_ktp_json, add_request, get_kelurahan, show_all_request_ktp_json, add_request_flutter, show_request_ktp_json_flutter

app_name = 'kependudukan'

urlpatterns = [
    path('', show_kependudukan, name='show_kependudukan'),
    path('request-ktp', show_request_ktp, name='show_request_ktp'),
    path('request-ktp/get-kelurahan', get_kelurahan),
    path('json', show_json, name='show_json'),
    path('request-ktp/json', show_request_ktp_json, name='show_request_ktp_json'),
    path('all-request-ktp/json', show_all_request_ktp_json, name='show_all_request_ktp_json'),
    path('request-ktp/add', add_request, name='add_request'),
    path('request-ktp/add-flutter', add_request_flutter, name='add_request_flutter'),
    path('request-ktp/json-flutter', show_request_ktp_json_flutter, name='show_request_ktp_json_flutter'),

    
]

kesehatan/urls.py
from django.urls import path
from .views import show_main, registrasi, show_healthFacility, show_healthFacility_json, show_appointment_json, create_appointment, delete_appointment, show_registered_patient_page, get_appointment_flutter_json_by_userId, get_patient_flutter_by_userId, add_patient_flutter, add_appointment_flutter, delete_appointment_flutter

app_name = 'kesehatan'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('health-facility/', show_healthFacility, name='health-facility'),
    path('health-facility/json/', show_healthFacility_json, name="health-facility-json"),
    path('registrasi/', registrasi, name='registrasi'),
    path('create-appointment/', create_appointment, name='create-appointment'),
    path('delete-appointment/<int:id>', delete_appointment, name='delete-appointment'),
    path('registered-patient/', show_registered_patient_page, name='registered-patient'),
    path('create-appointment/json/', show_appointment_json, name='appointment-json'),
    path('create-appointment-flutter/', add_appointment_flutter, name='create-appointment-flutter'),
    path('create-appointment-flutter/<int:id>/json', get_appointment_flutter_json_by_userId, name="appointment-json-by-id"),
    path('show-patient-flutter/<int:id>/json', get_patient_flutter_by_userId, name="appointment-json-by-id"),
    path('registrasi-flutter/', add_patient_flutter, name='add-patient-appointment'),
     path('delete-appointment-flutter/<int:id>', delete_appointment_flutter, name='delete-appointment-flutter'),
]

perpustakaan/urls.py
from django.urls import path
from .views import (get_book, get_book_by_id_json, get_book_json, get_book_by_id,
                    get_book_review_id_json,get_book_history_active_id_json,
                    get_book_history_done_id_json, get_author_by_id_json, get_publisher_by_id_json,
                    borrow, review, return_book, borrow_json, return_book_json, review_json)
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from depoksmartcity import settings

app_name = 'perpustakaan'

urlpatterns = [
    path('', get_book, name='get_book'),
    path('json', get_book_json, name='get_book_json'),
    path('book/<int:id>', get_book_by_id, name='get_book_by_id'),
    path('book/<int:id>/json', get_book_by_id_json, name='get_book_by_id_json'),
    path('author/<int:id>/json', get_author_by_id_json, name="get_author_by_id_json"),
    path('publisher/<int:id>/json', get_publisher_by_id_json, name="get_publisher_by_id_json"),
    path('book/borrow/<int:id>', borrow, name='borrow'),
    path('book/<int:id>/borrow', borrow_json, name='borrow_json'),
    path('book/return/<int:id>', return_book, name='return_book'),
    path('book/<int:id>/return', return_book_json, name='return_book_json'),
    path('book/review/<int:id>', review, name='review'),
    path('book/<int:id>/review', review_json, name='review_json'),
    path('book/history/active/<int:id>', get_book_history_active_id_json, name='get_book_history_active_id_json'),
    path('book/history/done/<int:id>', get_book_history_done_id_json, name='get_book_history_done_id_json'),
    path('book/review/<int:id>/json', get_book_review_id_json, name='get_book_review_id_json'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

restaurants/urls.py
from django.urls import path
from restaurants.views import show_restaurants
from restaurants.views import show_json
from restaurants.views import review_json
from restaurants.views import create_review

app_name = 'restaurants'

urlpatterns = [
    path('', show_restaurants, name='restaurants'),
    path('json/', show_json, name='json'),
    path('json-rev/<int:pk>', review_json, name='rev_json'),
    path('create-review/', create_review, name='create-review')
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import redirect
from django.http.response import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
import json

def index(request):
    return render(request, 'index.html')

@csrf_exempt
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('homepage:index')
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

@csrf_exempt
def login_flutter(request):
    print("MASUK DISINI")
    data = json.loads(request.body)
    username = data['username']
    password = data['password']

    if request.method == 'POST':
        user = authenticate(username=username, password=password)
        temp = User.objects.get(username=username)
        print(temp.id)
        print("AUTENTHICATE")
        print(username)
        print(password)
        if user is not None:
            login(request, user)
            return JsonResponse({
                "status": True,
                "username": request.user.username,
                "id": temp.id,
                "message": "Successfully Logged In!"
            }, status=200)

        else:
             return JsonResponse({
                "status": False,
                "message": "Failed to Login!"
            }, status=401)
    else:
        return JsonResponse({
            "status": False,
            "message": "Failed to Login, your username/password may be wrong."
        }, status=401)

@csrf_exempt
def logout_flutter(request):
    logout(request)
    return JsonResponse({
            "status": True,
            "message": "Berhasil"
        }, status=200)

def logout_user(request):
    logout(request)
    return redirect('homepage:login')

@csrf_exempt
def register_user(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        print(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('homepage:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

@csrf_exempt
def register_flutter(request):
    data = json.loads(request.body)
    username = data['username']
    password = data['password']
    confirm_pass = data['confirm_password']
    print(username)
    print(password)
    print(confirm_pass)

    if (password == confirm_pass):
        try:
        #Cek jika username atau email sudah terdaftar
            user = User.objects.get(username=username)
            print(user)
            return JsonResponse({'status':'register gagal'})
        except (User.DoesNotExist):
        #Jika username belum terdaftar
            user = User.objects.create_user(username=username, password=password)
            return JsonResponse({'status':'register berhasil', 'username':username, 'password':password})

homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Depok Smart City</title>
<head>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href={% static 'bootstrap.css' %} />
  <!-- font awesome style -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

  <!-- Custom styles for this template -->
  <link href={% static 'style.css' %} rel="stylesheet" />
</head>
{% endblock meta %}

{% block content %}
<div class="hero_area">
  <!-- header section strats -->
  <header class="header_section">
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="{% url 'homepage:index' %}">
          <span>
            Depok Smart City
          </span>
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class=""> </span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link pl-lg-0" href="{% url 'kependudukan:show_kependudukan' %}"> Kependudukan </a>
            </li>

            <li class="nav-item active">
              <a class="nav-link pl-lg-0" href="{% url 'restaurants:restaurants' %}"> Restoran </a>
            </li>

            <li class="nav-item active">
              <a class="nav-link pl-lg-0" href="{% url 'kesehatan:show_main' %}"> Kesehatan </a>
            </li>

            <li class="nav-item active">
              <a class="nav-link pl-lg-0" href="{% url 'perpustakaan:get_book' %}"> Perpustakaan </a>
            </li>

            <li class="nav-item active">
              <a class="nav-link pl-lg-0" href="{% url 'aspirasi:show_aspirasi' %}"> Aspirasi </a>
            </li>

            {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Hello, {{user.get_username}}!
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'homepage:logout' %}">Logout</a></li>
              </li>
            
            {% else %}
              <li class="nav-item active">
                <a class="nav-link pl-lg-0" href="{% url 'homepage:login' %}"> Login </a>
              </li>
            {% endif %}
          </ul>
        </div>
        
      </nav>
    </div>
  </header>
  <!-- end header section -->
  <!-- slider section -->
  <section class="slider_section ">
    <div id="customCarousel1" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="container ">
            <div class="row">
              <div class="col-md-6">
                <div class="detail-box">
                  <h5>
                    Depok Smart City
                  </h5>
                  <h1>
                    Everything <br>
                    in one site
                  </h1>
                  <p>
                    Depok Smart City adalah Website Kota Depok dengan berbagai fitur dalam satu website. Fitur-fitur tersebut antara lain kependudukan, aspirasi, restoran, perpustakaan, dan kesehatan.
                  </p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="img-box">
                  <img src="images/slider-img.png" alt="">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- end slider section -->
  <section class="slider_section ">
    <div id="customCarousel1" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <div class="container ">
            <div class="row">
              <div class="col-md-6">
                <div class="detail-box">
                  <h5>
                    About Us
                  </h5>
                  <h1>
                    PBP F04 <br>
                    Depok Smart City
                  </h1>
                  <p>
                    Kelompok F04 PBP Fasilkom UI Semester Gasal 2022/2023. <br>
                    1. Bagas Shalahuddin Wahid - 2106708904 <br>
                    2. Maureen Esther Wijaya - 2106705335 <br>
                    3. Muhammad Abizar Rachmanda - 2106751133 <br>
                    4. Muhammad Arief Braja Putra - 2106702352 <br>
                    5. Muhammad Rizqy Ramadhan - 2106632182 <br>
                  </p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="img-box">
                  <img src="images/slider-img.png" alt="">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>
{% endblock content %}

homepage/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<nav class="navbar" style="background-color: #232b2b;">
    <div class="container-fluid">
      <span class="navbar-brand mb-0 h1"> <b style="color:white">Login Page</b></span>
    </div>
</nav>

<div class = "login" style="text-align:center">
    <h1 style="margin-top: 25px">Login</h1>
    <form method="POST" action="" >
        {% csrf_token %}
        <table style="margin-left:auto;margin-right:auto; margin-top: 25px" class="table table-bordered w-auto">
            <tr>
                <td style="vertical-align: middle">Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td style="vertical-align: middle">Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>
        </table>
        <td><input class="btn btn-primary" type="submit" value="Login"></td>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     

    Belum mempunyai akun? <a href="{% url 'homepage:register' %}">Buat Akun</a>
        

</div>

{% endblock content %}

homepage/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<div class="vh-100" style="background-color: #60c7cb;">
    <div class="container py-5 h-100">
        <div class="d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
                <div class="card" style="border-radius: 1rem;">
                    <div class="col-md-12 col-lg-15 d-flex align-items-center">
                        <div class="card-body p-4 p-lg-5 text-black">

                            <form method="POST" action="">
                                {% csrf_token %}

                                <div class="d-flex align-items-center mb-3 pb-1">
                                    <label class="h1 fw-bold mb-0">Registration Form</label>
                                </div>
            
                                <div class="mb-4">
                                    {{ form.username.label_tag }}
                                    {{ form.username}}
                                </div>

                                <div class="form-outline mb-4">
                                    {{ form.password1.label_tag }}
                                    {{ form.password1 }}
                                </div>

                                <div class="form-outline mb-4">
                                    {{ form.password2.label_tag }}
                                    {{ form.password2 }}
                                </div>

                                <div class="pt-1 mb-4">
                                    <button class="btn btn-dark btn-lg btn-block" type="submit">Daftar</button>
                                </div>
                                
                                {% if messages %}  
                                <ul>   
                                    {% for message in messages %}  
                                        <li class="pb-2" style="color: #393f81;">{{ message }}</li>  
                                        {% endfor %}  
                                </ul>   
                                {% endif %}
                                   
                            </form>
                        </div>   
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}