aspirasi/urls.py
from django.urls import path
from aspirasi.views import show_aspirasi, show_json, add_aspirasi_ajax, show_aspirasi_pendatang, show_json_user, show_json_user, show_aspirasi_user, add_aspirasi_flutter

app_name = 'aspirasi'

urlpatterns = [
    path('', show_aspirasi, name='show_aspirasi'),
    path('json/', show_json, name='show_json'),
    path('add/', add_aspirasi_ajax, name='add_aspirasi_ajax'),
    path('show-aspirasi/', show_aspirasi_pendatang, name='show_aspirasi_pendatang'),
    path('json-user/', show_json_user, name='show_json_user'),
    path('aspirasi-user/', show_aspirasi_user, name='show_aspirasi_user'),
    path('add-aspirasi-flutter/', add_aspirasi_flutter, name='show_aspirasi_flutter'),



]

depoksmartcity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from depoksmartcity import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('kependudukan/', include('kependudukan.urls')),
    path('perpustakaan/', include('perpustakaan.urls')),
    path('aspirasi/', include('aspirasi.urls')),
    path('restaurants/', include('restaurants.urls')),
    path('kesehatan/', include('kesehatan.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

homepage/urls.py
from django.urls import path
from .views import index, login_user, register_user, logout_user, login_flutter, register_flutter, logout_flutter

app_name = 'homepage'

urlpatterns = [
    path('', index, name='index'),
    path('login/', login_user, name='login'),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    path('logout-flutter/', logout_flutter, name='logout_flutter'),
    path('login-flutter/', login_flutter, name='login_flutter'),
    path('register-flutter/', register_flutter, name='register_flutter'),

]

perpustakaan/urls.py
from django.urls import path
from .views import (get_book, get_book_by_id_json, get_book_json, get_book_by_id,
                    get_book_review_id_json,get_book_history_active_id_json,
                    get_book_history_done_id_json, get_author_by_id_json, get_publisher_by_id_json,
                    borrow, review, return_book, borrow_json, return_book_json, review_json)
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from depoksmartcity import settings

app_name = 'perpustakaan'

urlpatterns = [
    path('', get_book, name='get_book'),
    path('json', get_book_json, name='get_book_json'),
    path('book/<int:id>', get_book_by_id, name='get_book_by_id'),
    path('book/<int:id>/json', get_book_by_id_json, name='get_book_by_id_json'),
    path('author/<int:id>/json', get_author_by_id_json, name="get_author_by_id_json"),
    path('publisher/<int:id>/json', get_publisher_by_id_json, name="get_publisher_by_id_json"),
    path('book/borrow/<int:id>', borrow, name='borrow'),
    path('book/<int:id>/borrow', borrow_json, name='borrow_json'),
    path('book/return/<int:id>', return_book, name='return_book'),
    path('book/<int:id>/return', return_book_json, name='return_book_json'),
    path('book/review/<int:id>', review, name='review'),
    path('book/<int:id>/review', review_json, name='review_json'),
    path('book/history/active/<int:id>', get_book_history_active_id_json, name='get_book_history_active_id_json'),
    path('book/history/done/<int:id>', get_book_history_done_id_json, name='get_book_history_done_id_json'),
    path('book/review/<int:id>/json', get_book_review_id_json, name='get_book_review_id_json'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perpustakaan/models.py
from email.policy import default
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
import os

# Create your models here.
class Author(models.Model):
    first_name = models.CharField(max_length=25)
    middle_name = models.CharField(max_length=25, null=True, blank=True)
    last_name = models.CharField(max_length=25)
    email = models.EmailField()

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=75)
    city = models.CharField(max_length=50)
    state_province = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    website = models.URLField()

class Book(models.Model):                                            
    title = models.CharField(max_length=50)
    isbn = models.CharField(max_length=13, null=True, blank=True)
    synopsis = models.TextField()
    pages = models.IntegerField(validators=[MinValueValidator(1)])
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE)
    edition = models.IntegerField(default=1, validators=[MinValueValidator(1)])
    publication_date = models.DateField()
    photo = models.URLField(default='')
    stock = models.IntegerField(default=1, validators=[MinValueValidator(0)])
    is_available = models.BooleanField(default=True)
    rate = models.DecimalField(max_digits=3, decimal_places=2, validators=[MinValueValidator(0), MaxValueValidator(5)], default=0)
    borrowed_times = models.IntegerField(default=0)
    review_times = models.IntegerField(default=0)
    

class BookReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rate = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    review = models.TextField()

class BookHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrow_date = models.DateField()
    return_date = models.DateField(null=True, blank=True)
    is_active = models.BooleanField(default=True)

perpustakaan/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator


class reviewForm(forms.Form):
    review = forms.CharField(label="review", max_length=256, min_length=1)
    rate = forms.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])

perpustakaan/views.py
from django.urls import reverse
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.contrib.auth.decorators import login_required
from perpustakaan.forms import reviewForm
from .models import Author, BookHistory, Publisher, Book, BookReview
from django.views.decorators.http import require_http_methods
import datetime
from django.views.decorators import csrf
import json

# Create your views here.
def get_author_by_id_json(request, id):
    author_data = Author.objects.filter(id=id)
    context = {'data': author_data}
    return HttpResponse(serializers.serialize("json", author_data), content_type="application/json")

def get_publisher_by_id_json(request, id):
    publisher_data = Publisher.objects.filter(id=id)
    context = {'data': publisher_data}
    return HttpResponse(serializers.serialize("json", publisher_data), content_type="application/json")

def get_book(request):
    book_data = Book.objects.all()
    context = {'data': book_data}
    return render(request, "home.html", context)

def get_book_json(request):
    book_data = Book.objects.all()
    context = {'data': book_data}
    return HttpResponse(serializers.serialize("json", book_data), content_type="application/json")

def get_book_by_id(request, id):
    book_data = Book.objects.get(id=id)
    author_id = book_data.author.id
    publisher_id = book_data.publisher.id
    context = {'data': book_data,
                'id': id,
                'author_id': author_id,
                'publisher_id': publisher_id}
    return render(request, "book_id.html", context)

def get_book_by_id_json(request, id):
    book_data = Book.objects.filter(id=id)
    context = {'data': book_data}
    return HttpResponse(serializers.serialize("json", book_data), content_type="application/json")

def get_book_review_id_json(request, id):
    book = Book.objects.get(id=id)
    book_review_data = BookReview.objects.filter(book=book)
    context = {'data': book_review_data}
    return HttpResponse(serializers.serialize("json", book_review_data), content_type="application/json")

def get_book_history_active_id_json(request, id):
    book = Book.objects.get(id=id)
    book_history_data = BookHistory.objects.filter(book=book, user=request.user, is_active=True)
    return HttpResponse(serializers.serialize("json", book_history_data), content_type="application/json")

def get_book_history_done_id_json(request, id):   
    book = Book.objects.get(id=id)
    book_history_data = BookHistory.objects.filter(book=book, user=request.user, is_active=False)
    return HttpResponse(serializers.serialize("json", book_history_data), content_type="application/json")

@login_required(login_url='/login/')     
def borrow(request, id):
    user = request.user
    
    book = Book.objects.get(id=id)
    book.stock -= 1
    book.borrowed_times += 1
    
    if (book.stock == 0):
        book.is_available = False
    
    book.save()
    
    book_history = BookHistory.objects.create(user=user, book=book, borrow_date=datetime.datetime.now())
    book_history.save()
    return redirect('perpustakaan:get_book')

@login_required(login_url='/login/')     
def borrow_json(request, id):
    user = request.user
    
    book = Book.objects.get(id=id)
    book.stock -= 1
    book.borrowed_times += 1
    
    if (book.stock == 0):
        book.is_available = False
    
    book.save()
    
    book_history = BookHistory.objects.create(user=user, book=book, borrow_date=datetime.datetime.now())
    book_history.save()
    return HttpResponse(serializers.serialize("json", [book_history]), content_type="application/json")



@login_required(login_url='/login/')
def return_book(request, id):
    user = request.user
    
    book = Book.objects.get(id=id)
    book.stock += 1
    
    if (book.stock == 1):
        book.is_available = True
        
    book.save()   
        
    book_history = BookHistory.objects.filter(user=user, book=book, is_active=True)[0]
    book_history.is_active = False
    book_history.return_date = datetime.datetime.now()
    
    book_history.save()
    return redirect('perpustakaan:get_book')

@login_required(login_url='/login/')
def return_book_json(request, id):
    user = request.user
    
    book = Book.objects.get(id=id)
    book.stock += 1
    
    if (book.stock == 1):
        book.is_available = True
        
    book.save()   
        
    book_history = BookHistory.objects.filter(user=user, book=book, is_active=True)[0]
    book_history.is_active = False
    book_history.return_date = datetime.datetime.now()
    
    book_history.save()
    return HttpResponse(serializers.serialize("json", [book_history]), content_type="application/json")

@login_required(login_url='/login/')
def review(request, id):
    data = reviewForm(request.POST)
    
    if data.is_valid():
        user = request.user
        book = Book.objects.get(id=id)
        review = data.cleaned_data["review"]
        rate = data.cleaned_data["rate"]
        book_review = BookReview.objects.create(user=user, book=book, rate=rate, review=review)
        book_review.save()
        
        total_rate = book.rate * book.review_times
        total_rate += rate
        book.review_times += 1
        book.rate = total_rate/book.review_times
        book.save()
    return redirect('perpustakaan:get_book_by_id', id)

@require_http_methods(["POST"])
@csrf.csrf_exempt  
def review_json(request, id):
    if request.method == "POST":
        if request.COOKIES['sessionid'] != None:
            try:
                # flutter request sends data in body
                data = json.loads(request.body)
            except:
                # django sends html form (old fashioned way)
                data = reviewForm(request.POST).data

            user = request.user
            book = Book.objects.get(id=id)
            review = data["review"]
            rate = data["rate"]
            book_review = BookReview.objects.create(user=user, book=book, rate=rate, review=review)
            book_review.save()
            
            total_rate = book.rate * book.review_times
            total_rate += int(rate)
            book.review_times += 1
            book.rate = total_rate/book.review_times
            book.save()
            return JsonResponse({"status": "Success"}, status=201)
        return JsonResponse({"status": "Invalid input"}, status=400)
    else:
        response = JsonResponse({"status": "Invalid method"}, status=405)
        response['Allow'] = 'POST'
        return response

perpustakaan/templates/book_id.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title> e-Lib Depok</title>
<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href={% static 'bootstrap.css' %} />
    <!-- font awesome style -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
    <script src={% static 'book_id.js' %}>
    </script>
    <script>
      $(document).ready(function(){
        // For displaying task data
        $.get( "{% url 'perpustakaan:get_book_by_id_json' id %}", function(data) {
          bookData(data);      
        });
    
        $.get( "{% url 'perpustakaan:get_book_review_id_json' id %}", function(data) {
          reviewData(data);      
        });
    
        $.get( "{% url 'perpustakaan:get_book_history_active_id_json' id %}", function(data) {
          checkBorrowReturnButton(data);      
        });
    
        $.get( "{% url 'perpustakaan:get_book_history_done_id_json' id %}", function(data) {
          checkReviewButton(data);      
        });

        $.get( "{% url 'perpustakaan:get_author_by_id_json' author_id %}", function(data) {
          getAuthorName(data);      
        });

        $.get( "{% url 'perpustakaan:get_publisher_by_id_json' publisher_id %}", function(data) {
          getPublisherName(data);      
        });
    
      });
    </script>
    <!-- Custom styles for this template -->
    <link href={% static 'style.css' %} rel="stylesheet" />
</head>

{% endblock meta %}

{% block content %}

<div>
  <!-- header section strats -->
  <header class="header_section">
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg custom_nav-container ">
        <a class="navbar-brand" href="{% url 'perpustakaan:get_book' %}">
          <span>
            e-Lib Depok
          </span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class=""> </span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link pl-lg-0" href="{% url 'homepage:index' %}"> Home </a>
            </li>

            {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Hello, {{user.get_username}}!
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'homepage:logout' %}">Logout</a></li>
              </li>
            
            {% else %}
              <li class="nav-item active">
                <a class="nav-link pl-lg-0" href="{% url 'homepage:login' %}"> Login </a>
              </li>
            {% endif %}
          </ul>
        </div>
        
      </nav>
    </div>
  </header>
</div>
<div class="container">
  <div class="card">
    <div class="container-fluid">
      <div class="wrapper row">
        <div class="details col-md-6">
          <h3 class="product-title" id="book-title"></h3>
          <div class="rating" id="book-rate">
            <div class="stars" id="book-stars">
              <span class="fa fa-star" id="star1"></span>
              <span class="fa fa-star" id="star2"></span>
              <span class="fa fa-star" id="star3"></span>
              <span class="fa fa-star" id="star4"></span>
              <span class="fa fa-star" id="star5"></span>
            </div>
            <img id='book-cover'>
            <span class="review-no" id="book-review"></span>
            <br></br>
            <span class="review-no" id="author"></span>
            <br></br>
            <span class="review-no" id="publisher"></span>
            <br></br>
            <span class="review-no" id="publication_date"></span>
            <br></br>
            <span class="review-no" id="isbn"></span>
            <br></br>
            <span class="review-no" id="edition"></span>
            <br></br>
            <span class="review-no" id="pages"></span>
            <br></br>
            <span class="review-no" id="stock"></span>
          </div>
          <p class="product-description" id="book-synopsis"></p>

          {% if user.is_authenticated %}
          <div class="action">
            <form action="{% url 'perpustakaan:borrow' id %}" id="borrowForm">
              {% csrf_token %}
              <button class="btn btn-default borrow" type="submit" form="borrowForm" value="Submit" id="borrowBtn">Borrow</button>
            </form>

            <form action="{% url 'perpustakaan:return_book' id %}" id="returnForm">
              {% csrf_token %}
              <button class="btn btn-default borrow" type="submit" form="returnForm" value="Submit" id="returnBtn">Return</button>
            </form>


            <button class="btn btn-default review" type="button" id="reviewBtn" data-bs-toggle="modal" data-bs-target="#reviewModal">Review</button>
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>

<br>
<br>
<h3 class="product-title">Reviews: </h3>

<div class="container" id="review_list">
</div>

<div class="modal fade" id="reviewModal" tabindex="-1" aria-labelledby="add_review_modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="add_review_modal_label">Add Your Review</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="addReview" method="POST" action="{% url 'perpustakaan:review' id%}">
          {% csrf_token %}
  
              <p>Rate:</p>
              <input type="number" id="rate" name="rate" min="1" max="5">
              {% comment %} <input type="radio" id="rate1" value="1">
              <label for="rate1">1</label>
              <input type="radio" id="rate2" value="2">
              <label for="rate2">2</label>
              <input type="radio" id="rate3" value="3">
              <label for="rate3">3</label>
              <input type="radio" id="rate4" value="4">
              <label for="rate4">4</label>
              <input type="radio" id="rate5" value="5">
              <label for="rate5">5</label> {% endcomment %}
              <p>Review:</p>
              <textarea cols="100" id="review" rows="10" name="review" placeholder="Review" style="max-width: 100%;"></textarea><br/>
              
          <div style="margin: 10px auto;">
              <input class="btn btn-primary" type="submit" name="submit" value="Add">
          </div>

        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

perpustakaan/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title> e-Lib Depok</title>
<head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href={% static 'bootstrap.css' %} />
    <!-- font awesome style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Custom styles for this template -->
    <link href={% static 'style.css' %} rel="stylesheet" />
    <script src={% static 'home.js' %}>
    </script>
    <script>
    $(document).ready(function(){

        // For displaying book data
        $.get( "{% url 'perpustakaan:get_book_json' %}", function(data) {
          bookData(data);      
        });
    });
    </script>
</head>

{% endblock meta %}

{% block content %}

<div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container ">
          <a class="navbar-brand" href="{% url 'perpustakaan:get_book' %}">
            <span>
              e-Lib Depok
            </span>
          </a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a class="nav-link pl-lg-0" href="{% url 'homepage:index' %}"> Home </a>
              </li>

              {% if user.is_authenticated %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Hello, {{user.get_username}}!
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'homepage:logout' %}">Logout</a></li>
              </li>
            
            {% else %}
              <li class="nav-item active">
                <a class="nav-link pl-lg-0" href="{% url 'homepage:login' %}"> Login </a>
              </li>
            {% endif %}
            </ul>
          </div>
          
        </nav>
      </div>
    </header>
    <!-- end header section -->
    <!-- slider section -->
    <section class="slider_section ">
      <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container ">
              <div class="row">
                <div class="col-md-6">
                  <div class="detail-box">
                    <h5>
                      e-Lib Depok
                    </h5>
                    <h1>
                      For All Your <br>
                      Reading Needs
                    </h1>
                    <p>
                      e-Lib Depok adalah perpustakaan daring yang disediakan oleh pemerintah Kota Depok. Anda dapat meminjam buku secara daring. <br>
                      List Perpustakaan Luring Kota Depok: <br>
                      1. Perpustakaan Umum Kota Depok <br>
                      2. Perpustakaan Pusat Universitas Indonesia <br>

                    </p>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="images/slider-img.png" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- end slider section -->
    <section class="slider_section ">
      <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container ">
              <div class="row">
                <div class="col-md-6">
                  <div class="detail-box">
                    <h5>
                      Manfaat Membaca Buku
                    </h5>
                    <h1>
                      Membaca Buku itu <br>
                      Penting Lho!
                    </h1>
                    <p>
                      Buku adalah jendela dunia, dan kegiatan membaca buku merupakan suatu cara untuk membuka jendela tersebut agar kita bisa mengetahui lebih tentang dunia yang belum kita tahu sebelumnya.  Kegiatan tersebut dapat dilakukan oleh siapa saja, anak-anak, remaja, dewasa, maupun orang-orang yang telah berusia lanjut. <br>
                      Berikut manfaat membaca buku: <br>
                      1. Stimulasi Mental <br>
                      2. Mengurangi Stress <br>
                      3. Menambah Wawasan dan Pengetahuan <br>
                      4. Memperluas Pemikiran Seseorang <br>
                      5. Meningkatkan Kualitas Memori <br>
                      6. Meningkatkan Fokus dan Konsentrasi <br>
                      7. Meningkatkan Kemampuan Menulis <br>
                      
                    </p>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="img-box">
                    <img src="images/slider-img.png" alt="">
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>

    <!-- Products Start -->
    <div class="row" style="margin-left:10px; margin-right:10px" id="data">
    </div>
    <!-- Products End -->
{% endblock content %}